version: '3'

services:
  postgres: 
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: goexpert-client-server-api
    ports:
      - 5432:5432